### ISSUE TITLE
Log work and break time

### ISSUE THREAD

**Issue by cedewey** [Diego-Ivan/Flowtime#11]
I'm really enjoying Flowtime. One feature that would help me is being able to refer back to a log of my work and break times. 

One reason is because I track my time for work, so having a log to refer back to would make this easier than remembering to enter my time after every work period.

The other reason is so I can observe any behaviors that would be helpful to know. For example, see if there is a particular type of day I work for longer periods of time.

**Comment by Diego-Ivan** [comment]
Thanks for the suggestion!
I have been working for a little bit of time into implementing statistics in Flowtime. Currently, the plans are to keep records from the last 30 days of work. They will be shown into a separate view.

> For example, see if there is a particular type of day I work for longer periods of time.

I had not thought about this one, but it's actually a great idea. Do you mean getting the average worktime per day of the week? E.g, Mondays - 30 minutes, Tuesdays - 40 minutes and so on? That would be very interesting and it should not be complicated to implement.

Thanks for the ideas!

**Comment by Diego-Ivan** [comment]
I worked in how they can be displayed. Let me know what you think

![Stats 1](https://user-images.githubusercontent.com/76420970/163267140-fa30eb20-8d69-4c44-9104-e04943cf0c28.png)
![Stats 2](https://user-images.githubusercontent.com/76420970/163267150-2a9889c1-5de6-4d73-b111-78712fd86600.png)

**Comment by cedewey** [comment]
Nice!

What would work well for me is a chronological list of the work and break
sessions. Something like,

*April 13, 2022*

   - Work - 25:13
   - Break - 5:03
   - Work - 42:30
   - Break - 8:18


That would address the time tracking need. I think that list would also be
enough to analyze as well.

The sum by day and week wouldn't help me because I need to track the
specific tasks I'm working on and I like seeing how long each work session
is.

**Comment by Diego-Ivan** [comment]
I think it is a good idea too. I'll be working on it. Thanks for the suggestion!

**Comment by cedewey** [comment]
Awesome!

**Comment by Diego-Ivan** [comment]
So, I think it's pretty much done!
This is a small video on how it works. I kept the general statistics and renamed them to *Overview*, and I implemented day by day statistics separately. I also thought it would be cool if you could export your work and break statistics to CSV, so I also implemented that feature :smile:

Let me know what you think

https://user-images.githubusercontent.com/76420970/163650427-29d6d5b2-2d2f-4615-8567-0b482178cd44.mp4

**Comment by cedewey** [comment]
I love it! The stats are displayed nicely and the flow to get to more
granular stats is intuitive.

The CSV export I can see using too. That's a nice touch.

I look forward to using this new feature!

**Comment by Diego-Ivan** [comment]
I just merged the WIP Branch. I will be testing the feature this days in case I find any bugs. The update will be available by Monday on Flathub.

Thanks for your suggestions and feedback!
