### ISSUE TITLE
No Italian Language

### ISSUE THREAD

**Issue by albanobattistella** [Diego-Ivan/Flowtime#13]
HI,

I sow that Italian language is not available. Something wrong?
Thanks.
A.

**Comment by Diego-Ivan** [comment]
Thanks for reporting this issue! I'll be looking into it.

**Comment by Diego-Ivan** [comment]
I tested all translations and they seem to be working. Could you run Flowtime using `flatpak run io.github.diegoivanme.flowtime` and tell me if any warning or critical pops up?

**Comment by Diego-Ivan** [comment]
Updated translations have been published to Flathub, let me know if there are any issues :smile:

**Comment by albanobattistella** [comment]
> Updated translations have been published to Flathub, let me know if there are any issues smile

HI,
no issue..with translation, but not all words are translated.(probably no all are merged.)
Thanks.

**Comment by Diego-Ivan** [comment]
> but not all words are translated.(probably no all are merged.)

Thanks for pointing this out! I did not set some strings as translatable and therefore did not appear on the POT file either. I apologize for that. Now all of the UI words are translatable.

**Comment by Diego-Ivan** [comment]
As the PR has been merged, I'll be closing this issue. Thanks for your collaboration and contributions! 😄
