### ISSUE TITLE
Symbolic Icon

### ISSUE THREAD

**Issue by Diego-Ivan** [Diego-Ivan/Flowtime#21]
Flowtime has never had a proper symbolic icon, despite my numerous and failed attempts to create one. It is needed for the app's own identity, but I'm not able to come up with something nice. Any contributions are welcomed!

**Comment by daudix-UFO** [comment]
Hi, first, thank you for such an amazing and beautiful app!

I will try to make one very soon, maybe even with app icon redisign :D

**Comment by Diego-Ivan** [comment]
Thank you so much! I really appreciate it 😄

**Comment by daudix-UFO** [comment]
😊

**Comment by daudix-UFO** [comment]
Hello again, here is something looks like a symbolic + fresh app icon

![Снимок экрана от 2022-09-07 00-14-20](https://user-images.githubusercontent.com/77155297/188739920-3edcbf8d-b53d-4974-9fde-0c9844b18ab5.png)
![Снимок экрана от 2022-09-07 00-13-49](https://user-images.githubusercontent.com/77155297/188739928-21a2b3de-56ec-4a53-a1b3-dc06d07cb160.png)
![Снимок экрана от 2022-09-07 00-13-46](https://user-images.githubusercontent.com/77155297/188739932-a7ec4e60-eb0e-4de4-99e2-d384d2c71809.png)

**Comment by daudix-UFO** [comment]
A bit nicer symbolic icon, idea is: _Manage your **Free** time and **Work** time_

![изображение](https://user-images.githubusercontent.com/77155297/188937745-d10ac5f1-3b77-40cc-8f52-45348b592960.png)

**Comment by Diego-Ivan** [comment]
Hello, sorry for the late response. I love these icons! Thank you so much for your work, I reaally appreciate it! 😄

**Comment by daudix-UFO** [comment]
Any preferences before pull request?

**Comment by daudix-UFO** [comment]
#36
