### ISSUE TITLE
[Feature Request] Gnome-Shell Integration

### ISSUE THREAD

**Issue by starget24** [Diego-Ivan/Flowtime#22]
Basically just having an applet in the top bar in gnome or the equivalent in kde would be amazing, kinda like in the pomodoro gnome app (extension).

![Screenshot from 2022-04-30 06-58-34](https://user-images.githubusercontent.com/92924912/166104602-cae18e96-9dfd-4c5a-a251-0f17f5ec0074.png)

This at least for me would completely replace the pomodoro app, for the activities i actually like to do, and surely would be good for other people too. 
Keep up men, this app is really amazing.

**Comment by Diego-Ivan** [comment]
Hello there, thanks for your suggestion. 
I find this feature interesting, but it gets out of the scope that Flowtime has. Also, I believe something like this cannot be done by a sandboxed Flatpak application. Maybe, in the future I'll reconsider implementing this, but by the moment, it won't make it to Flowtime.

Anyways, thanks for your feedback and your gratitude! I'm glad you are enjoying my app :smile:

**Comment by Diego-Ivan** [comment]
@kchousos This is more viable now! I've been considering implementing a GNOME Shell extension, as Flowtime now has wider scope than it had two years ago, especially now with the screensaver feature which is kinda hacky as it is implemented now, a Shell Extension would help integrating Flowtime with the Shell. 

By the way, Flowtime currently now uses the XDG background apps status API, but it is pretty limited as it only shows the time and mode. 

I am currently tracking this issue in #87.
