### ISSUE TITLE
null is your most productive day of the week

### ISSUE THREAD

**Issue by raggesilver** [Diego-Ivan/Flowtime#23]
In **Statistics > Work Time** I see `(null) is your most productive day of the week` when opening the app for the first time.

![Screenshot from 2022-05-01 20-39-52](https://user-images.githubusercontent.com/16908491/166169403-95f06060-bd98-4ab6-9277-2c25698230bf.png)

**Comment by Diego-Ivan** [comment]
Thanks for reporting this issue! I will be implementing an empty mode for this cases

**Comment by Diego-Ivan** [comment]
Fixed! The update will be made available in a couple of days along with feature #20
