### ISSUE TITLE
List each work session in the statistic details view 

### ISSUE THREAD

**Issue by cedewey** [Diego-Ivan/Flowtime#24]
Thanks for rolling out the Statistics feature I requested. One aspect that was lost in translation is the detailed view. Rather than adding all of the work time up for each day, I would like a list of each work session. This allows me to both keep track of what I've done (eg: last work session I was designing a wireframe. I see here that I spent 25 minutes on it) and notice patterns (eg: I see I worked 3 fifteen minute sessions in the morning, but worked for an hour straight in the afternoon).

![ksnip_20220502-105503](https://user-images.githubusercontent.com/1270531/166291409-84a9c35f-3ade-4fe6-a7a3-ab06642869c0.png)

**Comment by Diego-Ivan** [comment]
Hello there! Thanks for you suggestion.

Unfortunately, I don't think I will be implementing this feature into Flowtime. Seems a little out of the scope that Flowtime tries to cover. I feel that the current implementation of statistics is just what the app needs.

Nevertheless, you may be interested in checking out some applications like [Khronos](https://beta.flathub.org/apps/details/io.github.lainsce.Khronos) or [Furtherance](https://beta.flathub.org/apps/details/com.lakoliu.Furtherance) to keep a more detailed log about your activities. These apps complement very well with Flowtime :)

If you have any other comments or suggestions, feel free to comment. I'll be pleased to hear your feedback.

**Comment by cedewey** [comment]
Ok, no problem. Thanks for considering my suggestion and for sharing the
related apps.
