### ISSUE TITLE
Flowtime (flatpak) fails to run in Pop!_OS 22.04

### ISSUE THREAD

**Issue by pchest** [Diego-Ivan/Flowtime#26]
Since upgrading to Pop!_OS 22.04, I have been unable to run Flowtime either by clicking on the application icon or by running it from the command line. When trying to run your application from the command line, I get the following output:

> flatpak run io.github.diegoivanme.flowtime

> /home/patrick/.var/app/io.github.diegoivanme.flowtime/data/statistics.xml:1: parser error : Document is empty

Hopefully this is something that can be easily fixed, I really do enjoy using your application.

Just a bit more information about my system: 

OS: Pop!_OS 22.04

Kernel: 5.17.5

DE: Gnome 42

GPU: Nvidia (x11)

**Comment by Diego-Ivan** [comment]
Hello there, thanks for reporting this issue. I'll be looking into it.

**Comment by Diego-Ivan** [comment]
Hello there! I've pushed a commit that should fix this issue, and it will be on Flathub very soon. In case it did not fix the problem, let me know in a comment :)
