### ISSUE TITLE
Make window draggable

### ISSUE THREAD

**Issue by pervoj** [Diego-Ivan/Flowtime#27]
The window is draggable only from the headerbar. But since there isn't any border on the bottom of the headerbar, it's hard to figure out.

For example Amberol or Kooha supports it.

https://user-images.githubusercontent.com/71781857/172048997-25cf521e-9345-40da-aeb9-9a8c1e621052.mp4

**Comment by Diego-Ivan** [comment]
I think this is a good idea. I'll implement it soon 😄
