### ISSUE TITLE
UI missing an icon

### ISSUE THREAD

**Issue by samkcdev** [Diego-Ivan/Flowtime#3]
Hi
Thanks for building this App.
Its seems like break button is missing an icon image
![image](https://user-images.githubusercontent.com/13085849/154246509-8b249bcf-8af9-42df-ad96-e54f6915bc14.png)

**Comment by Diego-Ivan** [comment]
Hi there, thanks for reporting this!
Flowtime is using mostly standard system icons. Said icon works well with Adwaita, elementary and Breeze icon themes. 
Could you provide more information regarding your icon theme?

**Comment by samkcdev** [comment]
I am using the Papirus Dark icon theme.

**Comment by samkcdev** [comment]
Thanks for looking into this. I reinstalled the app its working now

**Comment by Diego-Ivan** [comment]
I'm glad you could fix the issue 😄
