### ISSUE TITLE
Lock Screen option

### ISSUE THREAD

**Issue by prokoudine** [Diego-Ivan/Flowtime#32]
Personally, I find it convenient to have the screen locked for the duration of the break time (GNOME Pomodoro has this option) to get me out of the desk. The lock could be bypassed, but it would be an extra action.

Do you think it's something you would want to implement?

**Comment by Diego-Ivan** [comment]
Hello, thanks for your suggestion! I think it is a good idea, but Flowtime is limited as it is distributed as a Flatpak, and AFAIK there is no way to activate the screensaver. If a screensaver portal comes to existence, I will definitely implement this feature.

**Comment by prokoudine** [comment]
Wait, method name='SetActive' from https://github.com/flatpak/ppa-xdg-desktop-portal-gtk/blob/ppa/focal/data/org.freedesktop.ScreenSaver.xml is not what you need?

**Comment by Diego-Ivan** [comment]
Thanks! I will take a look into it

**Comment by sophie-h** [comment]
> is not what you need?

This is not the documentation of a flatpak portal but a DBus API used by the portal implementation.

It would probably work if you break through the sandbox with something like `--talk-name=org.freedesktop.ScreenSaver`

**Comment by Diego-Ivan** [comment]
@prokoudine This feature will finally land in 6.0 🥳. Thanks @sophie-h for the hint I needed for quite some time 😄
