### ISSUE TITLE
Timer won't start after break

### ISSUE THREAD

**Issue by nat212** [Diego-Ivan/Flowtime#4]
If I start a break, when the break is finished, and I click the next button, the timer doesn't start. I have to press the play/pause button a couple times to get it to start, and sometimes it starts incrementing by 2 seconds at a time.
I'm using Zorin OS 16 (built on Ubuntu 20.04) and it's installed through Flatpak.

**Comment by Diego-Ivan** [comment]
Thanks for reporting this issue!

I have tracked this issue down and I've been able to fix it. I'll push the fixes to Flathub very soon and an update will be available in around 3 hours.

**Comment by Diego-Ivan** [comment]
Build succeeded on Flathub. An update should be available in a few hours 😄
