### ISSUE TITLE
Looks like the "Autostart" behavior changed

### ISSUE THREAD

**Issue by zsdoma** [Diego-Ivan/Flowtime#43]
_Before I describe my problem, let me to tell, that this is a very good app, I like it very! Thank you! :)_

So, looks like the "Autostart" behavior changed since the last update and I'm not sure that the new behavior the expected or it is just a bug.

Before:
- Autostart enabled
- When the user click on the "Next stage" button in "Work stage", the stage switching to "Break stage" and the counter start ticking.
- After the counter reach zero, the user get a notification and the app waiting for some user action...
- When the user click on the "Next stage" button, the stage switching to "Work stage" and the counter timer start ticking automatically.

After:
- Autostart enabled
- When the "Next stage" button clicked in "Work stage", the stage switching but the counter doesn't start automatically.
- After the user start it manually and the counter reach zero, the stage change automatically and the "Work stage" timer start ticking...

Again, I'm not sure what the expected behavior here, but I think, the 'Before' behavior is better. The "Autostart" checkbox doesn't mention that the stage will change automatically, just to the timer will start automatically. Actually a little annoying to start the work stage automatically - the timer maybe start earlier than the user actually get beck to the laptop. But very convenient that the counter start when I change switch work stage (or switch to the break stage).

Flowtime version: 3.0

**Comment by Diego-Ivan** [comment]
Hi! It is, indeed, a bug. I'll fix it in a few minutes and an update will be available in a few hours.

Thanks for reporting it!
