### ISSUE TITLE
The app crashes when the next button is clicked without starting the timer.

### ISSUE THREAD

**Issue by TheOne04** [Diego-Ivan/Flowtime#49]
The title explains the issue. I'm using fedora Workstation 38 and the app crashes when I click the next button at 00:00.
I have the flatpak of the app.

In the GNOME problem reporting app I see:
reason: flowtime killed by SIGSEGV

**Comment by Diego-Ivan** [comment]
Thank you so much for reporting this issue! I will be pushing the fix to Flathub and should be available in a few hours, along with a runtime update :)
