### ISSUE TITLE
Shutdown hook to save work time?

### ISSUE THREAD

**Issue by tumbl3w33d** [Diego-Ivan/Flowtime#55]
Would it be possible to notice when the system is about to shutdown? My impression is that if I work for a while and suddenly decide to leave (i.e., shutdown my system), the work time is not saved. I got used to switch to break for no reason from time to time to not lose the work time I've spent but that seems wrong. A kind of "auto save" functionality might do as well.

**Comment by Diego-Ivan** [comment]
Thanks for the suggestion! Indeed, it is not saved as Flowtime does not handle that case, but shouldn't be hard to implement. I will be working on it soon
