### ISSUE TITLE
Allow decimal values for "break time divisor"

### ISSUE THREAD

**Issue by CactiChameleon9** [Diego-Ivan/Flowtime#63]
While dividing works well for controlling how much break you get per work, it currently lacks a lot of granularity.

Current values allow for: 50%, 33%, 25%, 20%, 17%, 14%, 12.5%, 11%, 10%

Say I wanted something like 40%, or a 3 divisor felt too long but 4 too short?

I therefore propose that you allow users to enter any decimal value in the text field, but keep the (+) and (-) buttons so it is user friendly

**Comment by Diego-Ivan** [comment]
I've been thinking about this feature and I think the percentages might work better than decimal divisors. A preference that allows the user to choose *Percentage of work time to take a break* sounds good to me. Limiting the values from 10% to 50% seems reasonable as well. What do you think?

**Comment by CactiChameleon9** [comment]
I think that would be more user friendly. I think people would have a better understanding of a percentage-based system

Can I suggest allowing a manual override of limits?
I like having +/- butttons (that say adjust by 5% in your 50%-10% range), but it would be useful for me to manually enter in 200% if, for example, I wanted to get a small amount of work done for a more chilled day.

**Comment by Diego-Ivan** [comment]
> Can I suggest allowing a manual override of limits? I like having +/- butttons (that say adjust by 5% in your 50%-10% range), but it would be useful to be able to manually type in 200% if, for example, I wanted to get a small amount of work done for a more chilled day.

Changing limits is a little bit more complicated. I limited it to 100%, it is more permissive than the 50% maximum I first thought of. Still, I believe going over that limit is somewhat against the principles of the Flowtime method, which is using it for tasks you enjoy doing. I do not want to limit the user's freedom more than that, and I doubt many users will decide to go over the 50% point anyways, the default and only possible value was 25% for quite a long time, which is the original time fraction for the Flowtime technique.
