### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by ideveCore** [Diego-Ivan/Flowtime#77]
I think it was supposed to be "5.0"
![Captura de tela de 2023-10-10 20-55-21](https://github.com/Diego-Ivan/Flowtime/assets/120337844/cea87e8f-a420-4a3b-9d1f-cc80c3f9f1ee)

**Comment by Diego-Ivan** [comment]
Sorry, I missed this. It should be 5.0, I'll push a fix soon. Thanks!
