### ISSUE TITLE
Make usage a little bit more self explenatory

### ISSUE THREAD

**Issue by tronta** [Diego-Ivan/Flowtime#8]
I really like the simple and clean design of the app… however it would be great, if it could be a little bit more self exploratory.
What happens when pressing the play button?
What happens when pressing the fast forward button?

Maybe a mouse over could help?
Or sth in the header?

**Comment by Diego-Ivan** [comment]
I will be looking into this.

I definitely believe that it should be a little more descriptive, maybe adding a tooltip to the buttons and indicating if the app is either on a work or break stage is necessary.

When I get home, I'll be making some changes and will update as soon as I can.

Thanks for the feedback! 😁

**Comment by tronta** [comment]
Thank you very much.
other idea. Maybe it would make sense if it could also change its color, so it's immediately visible what state it is in, or if it wants to say sth to me.

**Comment by Diego-Ivan** [comment]
![01 - Flowtime UI Tweaks](https://user-images.githubusercontent.com/76420970/158002530-04a09087-ecb2-40bc-a00f-84bbfa9c24f0.png)
This is one of the first ideas I had. I'll consider changing the accent color, I'm still deciding which ones should be chosen.

I was thinking keeping the green for the work stage and use purple or blue for the break stage.

**Comment by Diego-Ivan** [comment]
This is how both of the ideas look like: 

Green and Blue
![Kooha-03-11-2022-22-13-52](https://user-images.githubusercontent.com/76420970/158003272-3de48825-e11c-47af-bfd5-09a534747a3a.gif)

Green and Purple
![Kooha-03-11-2022-22-16-39](https://user-images.githubusercontent.com/76420970/158003320-30110121-9733-41b7-b9f1-d82ae5937909.gif)

**Comment by tronta** [comment]
My thoughts: What about keeping the standard theme when working. If I'm making a break, I might be not necessarily at my computer and therefore the whole window e.g. green.
![grafik](https://user-images.githubusercontent.com/5135577/158010654-172ae5a2-19ec-4395-9b6c-2f4122f6aba9.png)

**Comment by tronta** [comment]
An other thought, if fast forward is making a break, then a pause button would be also nice. Tbho I haven't still fully understood the concept :-) but maybe one could also use one button which is changing its symbol to pause…

**Comment by Diego-Ivan** [comment]
From my perspective, turning the whole window green isn't really an option. It will look odd in dark mode; changing accents, the stage indicator and the quote label are more than enough signs to tell the user that they have entered a different stage.

**Comment by Diego-Ivan** [comment]
The branch with the changes has been merged. Any other suggestion is welcomed! 😄

**Comment by tronta** [comment]
Cool, I'll have a look.
